title: <p align="center"> Omar Ayala</p>

logo: "images/fatasscatinatuxedo.jpg"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/darlin-soto-v%C3%A1squez-b97469105/">LinkedIn</a> |
  <a href="https://github.com/OmAyala">GitHub</a>
  </p>
  
  <p align="justify">
  I am Civil Engineering Mathematics student at Universidad de la Frontera, Chile.
  <br><br>
  I am studying.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
